// Pinpoint — per-country teaching data, keyed by the map name in countries.js.
//   [iso2, hook]
//   iso2 — ISO 3166-1 alpha-2, used for the flag image (flagcdn.com).
//   hook — one line that anchors the country to what surrounds it. Written
//          for an American player: neighbors, coastlines, landmarks, and the
//          odd fact that makes it stick.
window.META = {
  'Afghanistan': ['AF', 'Landlocked between Iran and Pakistan; the Hindu Kush runs through it.'],
  'Albania': ['AL', 'Adriatic coast facing the heel of Italy, just north of Greece.'],
  'Algeria': ['DZ', "Africa's largest country: Mediterranean coast up top, Sahara filling the rest."],
  'Andorra': ['AD', 'A Pyrenees microstate wedged between France and Spain.'],
  'Angola': ['AO', 'Atlantic coast south of the Congo; the big block above Namibia.'],
  'Antigua and Barb.': ['AG', 'Twin islands in the eastern Caribbean, near the top of the Lesser Antilles.'],
  'Argentina': ['AR', 'The long tail of South America, east of the Andes and Chile.'],
  'Armenia': ['AM', 'Landlocked in the Caucasus between Turkey and Azerbaijan.'],
  'Australia': ['AU', 'A continent to itself; Canberra sits inland between Sydney and Melbourne.'],
  'Austria': ['AT', 'Alpine, landlocked, east of Switzerland; Vienna on the Danube near Slovakia.'],
  'Azerbaijan': ['AZ', 'On the Caspian Sea east of Armenia; Baku juts out on a peninsula.'],
  'Bahamas': ['BS', 'Island chain just off Florida, north of Cuba.'],
  'Bahrain': ['BH', 'Tiny island in the Persian Gulf, connected by causeway to Saudi Arabia.'],
  'Bangladesh': ['BD', 'The Ganges delta, almost entirely wrapped by India, north of the Bay of Bengal.'],
  'Barbados': ['BB', 'The easternmost Caribbean island, out on its own in the Atlantic.'],
  'Belarus': ['BY', 'Landlocked between Poland and Russia, north of Ukraine.'],
  'Belgium': ['BE', 'North Sea coast between France and the Netherlands; Brussels near the middle.'],
  'Belize': ['BZ', 'Caribbean coast below Mexico’s Yucatán, east of Guatemala.'],
  'Benin': ['BJ', 'Narrow strip on the Gulf of Guinea between Togo and Nigeria.'],
  'Bhutan': ['BT', 'Himalayan kingdom tucked between India and Tibet, east of Nepal.'],
  'Bolivia': ['BO', 'Landlocked in the Andes; La Paz sits above Lake Titicaca, next to Peru.'],
  'Bosnia and Herz.': ['BA', 'Inland Balkans between Croatia and Serbia; a sliver of Adriatic coast.'],
  'Botswana': ['BW', 'The Kalahari, landlocked just north of South Africa.'],
  'Brazil': ['BR', "Half of South America; Brasília is inland, far from Rio and São Paulo."],
  'Brunei': ['BN', 'A small notch on the north coast of Borneo, inside Malaysia.'],
  'Bulgaria': ['BG', 'Black Sea coast south of Romania, north of Greece and Turkey.'],
  'Burkina Faso': ['BF', 'Landlocked in West Africa, north of Ghana, south of Mali.'],
  'Burundi': ['BI', 'Tiny, at the north end of Lake Tanganyika, just south of Rwanda.'],
  'Cabo Verde': ['CV', 'Atlantic islands 350 miles off Senegal, West Africa.'],
  'Cambodia': ['KH', 'Between Thailand and Vietnam; Phnom Penh on the Mekong.'],
  'Cameroon': ['CM', 'The hinge of Africa, where the west coast turns south; east of Nigeria.'],
  'Canada': ['CA', 'Ottawa is near the US border, between Toronto and Montreal.'],
  'Central African Rep.': ['CF', "Landlocked in the exact middle of Africa, north of the Congo."],
  'Chad': ['TD', 'Landlocked below Libya; Lake Chad on its western edge, Sudan to the east.'],
  'Chile': ['CL', 'The 2,600-mile ribbon on the Pacific side of the Andes.'],
  'China': ['CN', 'Beijing is in the northeast, inland from the Yellow Sea.'],
  'Colombia': ['CO', 'Top-left corner of South America, touching both Pacific and Caribbean.'],
  'Comoros': ['KM', 'Volcanic islands between Mozambique and the top of Madagascar.'],
  'Congo': ['CG', 'The smaller Congo, on the Atlantic side; Brazzaville faces Kinshasa across the river.'],
  'Costa Rica': ['CR', 'Between Nicaragua and Panama; San José in the central highlands.'],
  'Croatia': ['HR', 'The crescent hugging the Adriatic, wrapping around Bosnia.'],
  'Cuba': ['CU', 'The long island 90 miles south of Florida; Havana on the northwest coast.'],
  'Cyprus': ['CY', 'Island in the far eastern Mediterranean, south of Turkey.'],
  'Czechia': ['CZ', 'Landlocked heart of Europe, between Germany and Slovakia; Prague in the west.'],
  "Côte d'Ivoire": ['CI', 'Gulf of Guinea coast west of Ghana; the capital is inland Yamoussoukro, not Abidjan.'],
  'Dem. Rep. Congo': ['CD', 'The giant in the middle of Africa; Kinshasa on the river at its western edge.'],
  'Denmark': ['DK', 'The peninsula above Germany plus islands; Copenhagen faces Sweden.'],
  'Djibouti': ['DJ', 'Tiny, at the mouth of the Red Sea, across from Yemen.'],
  'Dominica': ['DM', 'Mountainous island between Guadeloupe and Martinique in the eastern Caribbean.'],
  'Dominican Rep.': ['DO', 'The eastern two-thirds of Hispaniola, sharing the island with Haiti.'],
  'Ecuador': ['EC', 'On the equator, Pacific coast, between Colombia and Peru.'],
  'Egypt': ['EG', "The Nile's northeast corner of Africa; Cairo at the top of the delta."],
  'El Salvador': ['SV', 'The small Pacific-only country in Central America, below Guatemala.'],
  'Eq. Guinea': ['GQ', 'A small mainland block below Cameroon; the capital Malabo is on an island offshore.'],
  'Eritrea': ['ER', 'Red Sea coast north of Ethiopia, which it split from.'],
  'Estonia': ['EE', 'Northernmost Baltic state, just across the gulf from Helsinki.'],
  'Ethiopia': ['ET', 'The Horn of Africa’s big landlocked highland; Addis Ababa in the center.'],
  'Fiji': ['FJ', 'South Pacific islands east of Australia, near the date line.'],
  'Finland': ['FI', 'East of Sweden, west of Russia; Helsinki on the south coast.'],
  'France': ['FR', 'Paris is in the north, on the Seine, closer to London than to the Riviera.'],
  'Gabon': ['GA', 'On the equator, Atlantic coast south of Cameroon.'],
  'Gambia': ['GM', 'A sliver along one river, entirely surrounded by Senegal.'],
  'Georgia': ['GE', 'Black Sea coast in the Caucasus, south of Russia, north of Turkey.'],
  'Germany': ['DE', 'Berlin is in the northeast, close to Poland.'],
  'Ghana': ['GH', 'Gulf of Guinea coast between Côte d’Ivoire and Togo; Accra on the shore.'],
  'Greece': ['GR', 'The southern tip of the Balkans plus islands; Athens near the bottom.'],
  'Grenada': ['GD', 'The "Spice Island," last stop at the southern end of the Lesser Antilles.'],
  'Guatemala': ['GT', 'Just south of Mexico; Guatemala City in the highlands.'],
  'Guinea': ['GN', 'West African coast between Guinea-Bissau and Sierra Leone.'],
  'Guinea-Bissau': ['GW', 'Small coastal country between Senegal and Guinea.'],
  'Guyana': ['GY', 'Northeast South America, east of Venezuela; Georgetown on the coast.'],
  'Haiti': ['HT', 'The western third of Hispaniola, between Cuba and the Dominican Republic.'],
  'Honduras': ['HN', 'The wide top of Central America; Tegucigalpa inland.'],
  'Hungary': ['HU', 'Landlocked on the Danube, south of Slovakia; Budapest split by the river.'],
  'Iceland': ['IS', 'Alone in the North Atlantic below the Arctic Circle; Reykjavík on the southwest coast.'],
  'India': ['IN', 'New Delhi is in the north, well inland, near the Pakistani border.'],
  'Indonesia': ['ID', 'The huge island arc; Jakarta on the northwest coast of Java.'],
  'Iran': ['IR', 'Between Iraq and Afghanistan; Tehran in the north below the Caspian.'],
  'Iraq': ['IQ', 'Between Syria and Iran; Baghdad on the Tigris in the middle.'],
  'Ireland': ['IE', 'West of Great Britain; Dublin on the east coast facing Wales.'],
  'Israel': ['IL', 'Eastern Mediterranean strip between Egypt and Lebanon.'],
  'Italy': ['IT', 'The boot; Rome halfway down the west coast.'],
  'Jamaica': ['JM', 'Island south of Cuba; Kingston on the southeast coast.'],
  'Japan': ['JP', 'Tokyo is on the Pacific side of the main island, about midway.'],
  'Jordan': ['JO', 'Landlocked-ish east of Israel, south of Syria; Amman in the northwest.'],
  'Kazakhstan': ['KZ', 'The giant below Russia; Astana in the north, not Almaty in the south.'],
  'Kenya': ['KE', 'East Africa on the equator; Nairobi in the south-center, inland.'],
  'Kiribati': ['KI', 'Scattered atolls on the equator in the central Pacific.'],
  'Kosovo': ['XK', 'Small landlocked patch between Serbia and Albania.'],
  'Kuwait': ['KW', 'At the top of the Persian Gulf, between Iraq and Saudi Arabia.'],
  'Kyrgyzstan': ['KG', 'Mountainous, landlocked, north of Tajikistan, west of China.'],
  'Laos': ['LA', 'The landlocked spine between Thailand and Vietnam; Vientiane on the Mekong.'],
  'Latvia': ['LV', 'The middle Baltic state; Riga on the gulf.'],
  'Lebanon': ['LB', 'Small Mediterranean coast north of Israel; Beirut on the shore.'],
  'Lesotho': ['LS', 'Mountain kingdom entirely inside South Africa.'],
  'Liberia': ['LR', 'West African coast southeast of Sierra Leone; Monrovia on the sea.'],
  'Libya': ['LY', 'Mediterranean coast between Egypt and Tunisia; Tripoli in the northwest.'],
  'Liechtenstein': ['LI', 'Alpine microstate between Switzerland and Austria.'],
  'Lithuania': ['LT', 'The southernmost Baltic state, above Poland.'],
  'Luxembourg': ['LU', 'Tiny, wedged between Belgium, Germany, and France.'],
  'Macedonia': ['MK', 'Landlocked, north of Greece, west of Bulgaria.'],
  'Madagascar': ['MG', 'The big island off the southeast coast of Africa.'],
  'Malawi': ['MW', 'Long and thin along Lake Malawi, between Zambia and Mozambique.'],
  'Malaysia': ['MY', 'The Malay Peninsula plus northern Borneo; Kuala Lumpur near the peninsula’s west coast.'],
  'Maldives': ['MV', 'Coral atolls in the Indian Ocean, southwest of the tip of India.'],
  'Mali': ['ML', 'Landlocked Sahara and Sahel; Bamako in the far southwest.'],
  'Malta': ['MT', 'Speck in the Mediterranean south of Sicily.'],
  'Marshall Is.': ['MH', 'Atolls in the central Pacific, north of the equator, east of Micronesia.'],
  'Mauritania': ['MR', 'Sahara on the Atlantic, above Senegal.'],
  'Mauritius': ['MU', 'Island in the Indian Ocean east of Madagascar.'],
  'Mexico': ['MX', 'Mexico City is in the south-central highlands, far from any coast.'],
  'Micronesia': ['FM', 'Islands in the western Pacific, north of Papua New Guinea.'],
  'Moldova': ['MD', 'Small and landlocked between Romania and Ukraine.'],
  'Monaco': ['MC', 'Two square miles on the French Riviera near the Italian border.'],
  'Mongolia': ['MN', 'Landlocked between Russia and China; Ulaanbaatar in the north-center.'],
  'Montenegro': ['ME', 'Small Adriatic coast south of Croatia, north of Albania.'],
  'Morocco': ['MA', 'Northwest corner of Africa, across the strait from Spain; Rabat on the Atlantic.'],
  'Mozambique': ['MZ', 'Long Indian Ocean coast facing Madagascar; Maputo at the very bottom.'],
  'Myanmar': ['MM', 'Between Bangladesh and Thailand; the capital Naypyidaw is inland, not Yangon.'],
  'Namibia': ['NA', 'Desert Atlantic coast above South Africa; Windhoek in the middle.'],
  'Nauru': ['NR', 'A single 8-square-mile island in the Pacific, just south of the equator.'],
  'Nepal': ['NP', 'Himalayas between India and Tibet; Kathmandu in a valley in the middle.'],
  'Netherlands': ['NL', 'Low country on the North Sea; Amsterdam near the coast, north of Belgium.'],
  'New Zealand': ['NZ', 'Two islands southeast of Australia; Wellington at the bottom of the North Island.'],
  'Nicaragua': ['NI', 'Largest Central American country, between Honduras and Costa Rica.'],
  'Niger': ['NE', 'Landlocked Sahara north of Nigeria; Niamey in the far southwest on the river.'],
  'Nigeria': ['NG', 'Gulf of Guinea, Africa’s most populous; Abuja is in the center, not Lagos.'],
  'North Korea': ['KP', 'Northern half of the Korean peninsula; Pyongyang in the west.'],
  'Norway': ['NO', 'The fjord coast running up the Scandinavian peninsula; Oslo at the bottom.'],
  'Oman': ['OM', 'Southeast corner of Arabia; Muscat on the Gulf of Oman.'],
  'Pakistan': ['PK', 'Between India and Afghanistan; Islamabad in the north near Kashmir.'],
  'Palau': ['PW', 'Small islands in the western Pacific, east of the Philippines.'],
  'Panama': ['PA', 'The isthmus connecting the Americas; the canal cuts through near Panama City.'],
  'Papua New Guinea': ['PG', 'Eastern half of New Guinea, north of Australia.'],
  'Paraguay': ['PY', 'Landlocked between Brazil, Argentina, and Bolivia; Asunción on the river.'],
  'Peru': ['PE', 'Pacific coast below Ecuador; Lima on the shore.'],
  'Philippines': ['PH', 'Island cluster north of Indonesia; Manila on Luzon in the north.'],
  'Poland': ['PL', 'Between Germany and Ukraine on the Baltic; Warsaw in the center.'],
  'Portugal': ['PT', 'West edge of Iberia; Lisbon on the Atlantic coast.'],
  'Qatar': ['QA', 'A thumb sticking into the Persian Gulf from Saudi Arabia.'],
  'Romania': ['RO', 'Black Sea coast north of Bulgaria; Bucharest in the south.'],
  'Russia': ['RU', 'Moscow is in the far west, closer to Poland than to Siberia.'],
  'Rwanda': ['RW', 'Small, hilly, west of Tanzania, north of Burundi.'],
  'S. Sudan': ['SS', 'Split from Sudan in 2011; landlocked north of Uganda.'],
  'Saint Lucia': ['LC', 'Eastern Caribbean island between Martinique and St. Vincent.'],
  'Samoa': ['WS', 'Polynesian islands in the South Pacific, northeast of Fiji.'],
  'San Marino': ['SM', 'Microstate on a hilltop inside northeastern Italy.'],
  'Saudi Arabia': ['SA', 'Most of the Arabian peninsula; Riyadh dead center.'],
  'Senegal': ['SN', 'Westernmost point of Africa; Dakar on the tip.'],
  'Serbia': ['RS', 'Landlocked center of the Balkans; Belgrade on the Danube.'],
  'Seychelles': ['SC', 'Granite islands in the Indian Ocean northeast of Madagascar.'],
  'Sierra Leone': ['SL', 'West African coast between Guinea and Liberia.'],
  'Singapore': ['SG', 'City-state on an island at the tip of the Malay Peninsula.'],
  'Slovakia': ['SK', 'Landlocked between Czechia and Hungary; Bratislava on the Danube next to Vienna.'],
  'Slovenia': ['SI', 'Alpine corner between Italy, Austria, and Croatia.'],
  'Solomon Is.': ['SB', 'Island chain east of Papua New Guinea.'],
  'Somalia': ['SO', 'The Horn of Africa’s coastline; Mogadishu on the Indian Ocean.'],
  'South Africa': ['ZA', 'Bottom of the continent; Pretoria is inland in the northeast, near Johannesburg.'],
  'South Korea': ['KR', 'Southern half of the peninsula; Seoul in the northwest near the border.'],
  'Spain': ['ES', 'Most of Iberia; Madrid dead center.'],
  'Sri Lanka': ['LK', 'Teardrop island off the southern tip of India.'],
  'St. Kitts and Nevis': ['KN', 'Two small islands in the northeast Caribbean, near Antigua.'],
  'St. Vin. and Gren.': ['VC', 'Eastern Caribbean chain between St. Lucia and Grenada.'],
  'Sudan': ['SD', 'Below Egypt on the Red Sea; Khartoum where the two Niles meet.'],
  'Suriname': ['SR', 'Northeast South America between Guyana and French Guiana.'],
  'Sweden': ['SE', 'East side of Scandinavia; Stockholm on the Baltic coast.'],
  'Switzerland': ['CH', 'Alpine, landlocked; the capital is Bern, not Zurich or Geneva.'],
  'Syria': ['SY', 'North of Jordan, east of Lebanon; Damascus in the southwest.'],
  'São Tomé and Principe': ['ST', 'Two islands in the Gulf of Guinea, off Gabon.'],
  'Taiwan': ['TW', 'Island 100 miles off China’s southeast coast; Taipei at the north end.'],
  'Tajikistan': ['TJ', 'Mountainous, landlocked, north of Afghanistan.'],
  'Tanzania': ['TZ', 'East Africa below Kenya; the capital is inland Dodoma, not Dar es Salaam.'],
  'Thailand': ['TH', 'Between Myanmar and Cambodia; Bangkok near the top of the gulf.'],
  'Timor-Leste': ['TL', 'Eastern half of Timor island, north of Australia.'],
  'Togo': ['TG', 'Thin strip on the Gulf of Guinea between Ghana and Benin.'],
  'Tonga': ['TO', 'Polynesian islands in the South Pacific, southeast of Fiji.'],
  'Trinidad and Tobago': ['TT', 'Islands just off the coast of Venezuela.'],
  'Tunisia': ['TN', 'North Africa’s northern tip, closest point to Sicily.'],
  'Turkey': ['TR', 'Bridge between Europe and Asia; Ankara inland in the middle, not Istanbul.'],
  'Turkmenistan': ['TM', 'Desert east of the Caspian, north of Iran.'],
  'Uganda': ['UG', 'Landlocked on Lake Victoria, west of Kenya; Kampala on the lake.'],
  'Ukraine': ['UA', 'Black Sea coast between Poland and Russia; Kyiv in the north on the Dnipro.'],
  'United Arab Emirates': ['AE', 'Persian Gulf coast east of Saudi Arabia; Abu Dhabi, not Dubai, is the capital.'],
  'United Kingdom': ['GB', 'London is in the southeast of Great Britain, on the Thames.'],
  'United States of America': ['US', 'Washington is on the East Coast between Maryland and Virginia.'],
  'Uruguay': ['UY', 'Small, on the Atlantic between Brazil and Argentina; Montevideo across from Buenos Aires.'],
  'Uzbekistan': ['UZ', 'Central Asia’s center; Tashkent in the far east near Kazakhstan.'],
  'Vanuatu': ['VU', 'Island chain in the South Pacific, west of Fiji.'],
  'Vatican': ['VA', 'The world’s smallest country, inside the city of Rome.'],
  'Venezuela': ['VE', 'Caribbean coast of South America; Caracas near the shore in the north.'],
  'Vietnam': ['VN', 'The S-curve on the South China Sea; Hanoi in the north, not Ho Chi Minh City.'],
  'Yemen': ['YE', 'Bottom of Arabia; Sana’a in the mountainous west.'],
  'Zambia': ['ZM', 'Landlocked above Zimbabwe; Victoria Falls on the border between them.'],
  'Zimbabwe': ['ZW', 'Landlocked between Zambia and South Africa; Harare in the northeast.'],
  'eSwatini': ['SZ', 'Small kingdom between South Africa and Mozambique.'],
};
